FROM nginx:latest

# Builds the environment files from js
COPY 40-environment-setup.sh /docker-entrypoint.d
RUN chmod +x /docker-entrypoint.d/40-environment-setup.sh

# Frontend files
COPY index.html /usr/share/nginx/html/index.html
COPY script.js /usr/share/nginx/html/script.js

EXPOSE 80