apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: augustodsgv/ffmpeg-backend
          imagePullPolicy: Always
          env:
          - name: DATABASE_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: database-endpoint
            # value: minio
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: database-port
            # value: "9000"
          - name: DATABASE_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: database-bucket-name
            # value: "bucket-teste"
          - name: DATABASE_USR
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: database-user
            # value: "minio"
          - name: DATABASE_PASSWD
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: database-passwd
            # value: "miniominio"