services:
  frontend:
    build: ./frontend_docker
    env_file:
      - variables.env
    ports:
    - "80:80"
    depends_on:
    - backend
  
  backend:
    build: ./backend
    env_file:
      - variables.env
    ports:
    - "7000:7000"
    volumes:
    - ./backend/data:/data
    depends_on:
      - database
    
  database:
    image: quay.io/minio/minio
    env_file:
      - variables.env
    ports:
    - "9001:9001"
    volumes:
    - ./db/data:/data
    command: server /data --console-address ":9001"