services:
  frontend:
    build: ./frontend
    ports:
    - "8080:80"
    env_file:
    - variables.env
    depends_on:
    - backend
  
  backend:
    build: ./backend
    env_file:       # Getting database user and passwd
      - variables.env
    ports:
    - "7000:7000"
    depends_on:
      - database
    
  database:
    image: quay.io/minio/minio
    env_file:
      - variables.env
    ports:
    - "9001:9001"
    - "9000:9000"
    volumes:
    - db-data:/data

    command: server /data --console-address ":9001"
  

volumes:
  db-data: