services:
  frontend:
    # image: ffmpeg-frontend:latest
    build: ./frontend
    env_file:
      - variables.env
    ports:
    - "8080:80"
    depends_on:
    - backend
  
  backend:
    # image: ffmpeg-backend:latest
    build: ./backend
    env_file:       # Getting database user and passwd
      - variables.env
    ports:
    - "7000:7000"
    volumes:
    - ./backend/data:/data
    depends_on:
      - database
    
  database:
    image: quay.io/minio/minio
    env_file:
      - variables.env
    ports:
    - "9001:9001"
    - "9000:9000"
    volumes:
    - ./db/data:/data
    command: server /data --console-address ":9001"