FROM ubuntu:latest
# Installing default ffpeg from apt
RUN apt update && apt upgrade -y
RUN printf "2\n134\n" | apt install ffmpeg -y

# python resources
RUN apt update && apt install python3 pip python3-venv -y
RUN python3 -m venv /home/venv

WORKDIR /home
ENV PATH="venv/bin:$PATH"
COPY ./requirements.txt .

RUN pip3 install -r requirements.txt
COPY ./src ./src

EXPOSE 7000

CMD python3 -m src.main