FROM ubuntu:latest
# Installing default ffpeg from apt
RUN apt update && apt upgrade -y
RUN printf "2\n134\n" | apt install ffmpeg -y

# python resources
RUN apt install python3 python3-pip -y
RUN apt install python3-venv -y

WORKDIR /home
RUN python3 -m venv env
COPY ./requirements.txt .
SHELL ["/bin/bash", "-c"]
RUN source ./env/bin/activate && pip3 install -r requirements.txt
COPY ./src ./src

EXPOSE 7000

CMD source ./env/bin/activate && python3 -m src.main