apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:  
      app: minio
  serviceName: minio
  replicas: 1

  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database-user
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database-passwd

        volumeMounts:
        - name: data
          mountPath: /data
        args: ['server', '--console-address', ':9001', '/data']

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: cinder-storageclass
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
